networks:
  acme-net:
    name: acme-net
    driver: bridge

services:

  config-server:
    image: ghcr.io/wwun/acme-shop-javabackend/config-server:latest
    container_name: config-server
    ports:
      - "8888:8888"
    networks:
      - acme-net
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8888/actuator/health | grep -q '\"status\"\\s*:\\s*\"UP\"'"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  eureka-server:
    image: ghcr.io/wwun/acme-shop-javabackend/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - acme-net
    depends_on:
      config-server:
        condition: service_healthy
      build-stage:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8761/actuator/health | grep -q '\"status\"\\s*:\\s*\"UP\"'"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
  
  user-service:
    image: ghcr.io/wwun/acme-shop-javabackend/user-service:latest
    container_name: user-service
    ports:
      - "8081:8001"
    networks:
      - acme-net
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy   
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_TOOL_OPTIONS=-Djava.net.preferIPv4Stack=true

  product-service:
    image: ghcr.io/wwun/acme-shop-javabackend/product-service:latest
    container_name: product-service
    ports:
      - "8077:8001"
    networks:
      - acme-net
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_TOOL_OPTIONS=-Djava.net.preferIPv4Stack=true
      
  order-service:
    image: ghcr.io/wwun/acme-shop-javabackend/order-service:latest
    container_name: order-service
    ports:
      - "8088:8001"
    networks:
      - acme-net
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_TOOL_OPTIONS=-Djava.net.preferIPv4Stack=true
      
  cart-service:
    image: ghcr.io/wwun/acme-shop-javabackend/cart-service:latest
    container_name: cart-service
    ports:
      - "8085:8001"
    networks:
      - acme-net
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      #- SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - JAVA_TOOL_OPTIONS=-Djava.net.preferIPv4Stack=true
      #- EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka

  auth-service:
    image: ghcr.io/wwun/acme-shop-javabackend/auth-service:latest
    container_name: auth-service
    ports:
      - "8089:8001"
    networks:
      - acme-net
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_TOOL_OPTIONS=-Djava.net.preferIPv4Stack=true
      - GOOGLE_CLIENT_ID=1072666433714-ohe6bue7h1bjeamcijs9ecdjli83i7f4.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - OAUTH2_REDIRECT_URI=http://localhost:8090/login/oauth2/code/{registrationId}
      # - ACME_JWT_SECRET=${ACME_JWT_SECRET}
      # - EUREKA_DEFAULT_ZONE=${EUREKA_DEFAULT_ZONE}

  inventory-service:
    image: ghcr.io/wwun/acme-shop-javabackend/inventory-service:latest
    container_name: inventory-service
    ports:
      - "8092:8001"
    networks:
      - acme-net
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_TOOL_OPTIONS=-Djava.net.preferIPv4Stack=true
      
  api-gateway-server:
    image: ghcr.io/wwun/acme-shop-javabackend/api-gateway-server:latest
    container_name: api-gateway-server
    ports:
      - "8090:8090"
    networks:
      - acme-net
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_TOOL_OPTIONS=-Djava.net.preferIPv4Stack=true
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
      user-service:
        condition: service_started
      product-service:
        condition: service_started
      order-service:
        condition: service_started
      cart-service:
        condition: service_started
      inventory-service:
        condition: service_started
      
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - acme-net
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - user-service
      - product-service
      - order-service
      - inventory-service
      - cart-service

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - acme-net
    depends_on:
      product-service:
        condition: service_started
      cart-service:
        condition: service_started

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - acme-net
    depends_on:
      - prometheus