package com.wwun.acme.product.dto;

import java.math.BigDecimal;
import java.util.UUID;

public class ProductResponseDTO {   //what the server responses with when a product is requested
                                    //id is included as it is generated by the server and is needed by the client to reference the product in future requests.
    private UUID id;
    private String name;
    private String description;
    private BigDecimal price;
    private Integer stock;
    private CategoryResponseDTO category;

    public UUID getId() {
        return id;
    }
    public void setId(UUID id) {
        this.id = id;
    }
    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return description;
    }
    public void setDescription(String description) {
        this.description = description;
    }
    public BigDecimal getPrice() {
        return price;
    }
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
    public Integer getStock() {
        return stock;
    }
    public void setStock(Integer stock) {
        this.stock = stock;
    }
    public CategoryResponseDTO getCategory() {
        return category;
    }
    public void setCategory(CategoryResponseDTO category) {
        this.category = category;
    }
    
}
