package com.wwun.acme.product.dto;

import java.math.BigDecimal;
import java.util.UUID;

public record ProductResponseDTO(UUID id, String name, String description, BigDecimal price, Integer stock, CategoryResponseDTO category){

}

    //what the server responses with when a product is requested
    //id is included as it is generated by the server and is needed by the client to reference the product in future requests.