#to be used by config server
spring:
    application:
        name: msvc-gateway
    config: 
        import: optional:configserver:http://config-server:8888

logging:
  level:
    org.springframework.security: DEBUG