name: Build and Publish Docker Images

on:
  push:
    branches: 
      - "main"

permissions:
  contents: read
  packages: write

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        
      - name: Install Java 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          
      - name: Build project
        run: mvn clean package -DskipTests
        
      - name: Log into GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        
      - name: Build docker images
        run: |
          docker build -t ghcr.io/${{ github.repository }}/product-service:${{ github.sha }} ./product-service
          docker build -t ghcr.io/${{ github.repository }}/order-service:${{ github.sha }} ./order-service
          docker build -t ghcr.io/${{ github.repository }}/user-service:${{ github.sha }} ./user-service
          docker build -t ghcr.io/${{ github.repository }}/config-server:${{ github.sha }} ./config-server
          docker build -t ghcr.io/${{ github.repository }}/inventory-service:${{ github.sha }} ./inventory-service
        
      - name: Push Docker images
        run: |
          docker push ghcr.io/${{ github.repository }}/product-service:${{ github.sha}}
          docker push ghcr.io/${{ github.repository }}/order-service:${{ github.sha}}
          docker push ghcr.io/${{ github.repository }}/user-service:${{ github.sha}}
          docker push ghcr.io/${{ github.repository }}/config-server:${{ github.sha}}
          docker push ghcr.io/${{ github.repository }}/inventory-service:${{ github.sha }}
